POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InowaHZpIiwiaWQiOiI2NTFhNmI5ZDg3YjVhZjgzOTIyYTkyNGUiLCJpYXQiOjE2OTYzMjMzOTh9.oH7khHA7jCMRV05m7l2KRMVZfnXMgww1qTYKenxHynQ

{
    "title": "Why You Really Should Stop Drinking",
    "author": "DUI",
    "url": "https://tequila.com",
    "likes": 1
}
