POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "You Won't Believe How Much Sleep Is Actually Enough",
    "author": "Sleepwalker",
    "url": "https://sleepingrocks.com",
    "likes": 17,
    "userId": "651a6b9d87b5af83922a924e"
}
